name: Secure Vault Pipeline

on: [push]

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codi del repositori
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instal·lar Selenium i dependències
        run: |
          pip install selenium

      - name: "Pas 1: Unit Testing (TDD)"
        run: |
          python3 -m unittest test_vault.py

      - name: "Pas 2: Security Scan (Selenium Atac)"
        run: |
          # Executem el bot. Si troba la vulnerabilitat, farà exit(1) i la pipeline fallarà (vermell)
          python3 attack_bot.py
